### ISSUE TITLE
llama2 worker fails when running docker compose up

### ISSUE THREAD

**Issue by kim-liedtke** [luisroque/large_laguage_models#5]
```
[2023-08-02 15:04:42,516: ERROR/ForkPoolWorker-2] Signal handler <function setup_model at 0x7fff54075940> raised: ValueError('\n                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit\n                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping\n                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom\n                        `device_map` to `from_pretrained`. Check\n                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu\n                        for more details.\n                        ')
2023-08-02T15:04:42.520536010Z Traceback (most recent call last):
2023-08-02T15:04:42.520538718Z   File "/usr/local/lib/python3.9/site-packages/celery/utils/dispatch/signal.py", line 276, in send
2023-08-02T15:04:42.520540677Z     response = receiver(signal=self, sender=sender, **named)
2023-08-02T15:04:42.520542260Z   File "/app/celery_worker.py", line 21, in setup_model
2023-08-02T15:04:42.520543885Z     model_loader = ModelLoader(model_path)
2023-08-02T15:04:42.520545760Z   File "/app/model_loader.py", line 16, in __init__
2023-08-02T15:04:42.520547635Z     self.model = self._load_model()
2023-08-02T15:04:42.520549427Z   File "/app/model_loader.py", line 22, in _load_model
2023-08-02T15:04:42.520551052Z     model = AutoModelForCausalLM.from_pretrained(
2023-08-02T15:04:42.520553510Z   File "/usr/local/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 484, in from_pretrained
2023-08-02T15:04:42.520557593Z     return model_class.from_pretrained(
2023-08-02T15:04:42.520559093Z   File "/usr/local/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2819, in from_pretrained
2023-08-02T15:04:42.520560718Z     raise ValueError(
2023-08-02T15:04:42.520562218Z ValueError: 
2023-08-02T15:04:42.520563760Z                         Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
2023-08-02T15:04:42.520565427Z                         the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
2023-08-02T15:04:42.520567177Z                         these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
2023-08-02T15:04:42.520568760Z                         `device_map` to `from_pretrained`. Check
2023-08-02T15:04:42.520571135Z                         https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
2023-08-02T15:04:42.520572802Z                         for more details.
```

**Comment by luisroque** [comment]
Hey @kim-liedtke, it seems that you don't have enough VRAM. You can try to quantize it further.
